<Project>
  <PropertyGroup>
    <Version>2.0.0</Version>
    <Authors>eQuantic Tech</Authors>
    <Copyright>2026 eQuantic Tech</Copyright>
    <PackageProjectUrl>https://github.com/eQuantic/core-validation</PackageProjectUrl>
    <RepositoryUrl>https://github.com/eQuantic/core-validation</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageOutputPath>$(MSBuildThisFileDirectory)artifacts/</PackageOutputPath>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <NeutralLanguage>en</NeutralLanguage>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)LICENSE" Pack="true" PackagePath="" Link="LICENSE" />
    <None Include="$(MSBuildProjectDirectory)/README.md" Pack="true" PackagePath="" />
    <None Include="$(MSBuildProjectDirectory)/Icon.png" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
