using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace eQuantic.Validation.Generator;

/// <summary>Emits validator classes and DI registration source for discovered descriptors.</summary>
internal static class ValidatorEmitter
{
    public const string MissingRegistrationDependenciesId = "VALGEN001";
    public const string CustomRuleMethodMissingId = "VALGEN002";
    public const string ElementTypeUnresolvedId = "VALGEN003";
    public const string UnsupportedTargetId = "VALGEN004";

    private static readonly DiagnosticDescriptor MissingRegistrationDependencies = new(
        id: MissingRegistrationDependenciesId,
        title: "Generated validator registration requires eQuantic.Validation and Microsoft.Extensions.DependencyInjection.Abstractions",
        messageFormat: "Reference eQuantic.Validation and Microsoft.Extensions.DependencyInjection.Abstractions to enable AddGeneratedValidation()",
        category: "Validation",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "The generated registration method calls the core validation registration extensions.");

    private static readonly DiagnosticDescriptor CustomRuleMethodMissing = new(
        id: CustomRuleMethodMissingId,
        title: "CustomRule method not found",
        messageFormat: "{0}",
        category: "Validation",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor ElementTypeUnresolved = new(
        id: ElementTypeUnresolvedId,
        title: "ValidateEach element type could not be resolved",
        messageFormat: "{0}",
        category: "Validation",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor UnsupportedTarget = new(
        id: UnsupportedTargetId,
        title: "Validation rule or target is not supported by the generator",
        messageFormat: "{0}",
        category: "Validation",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public static void EmitModelValidator(SourceProductionContext context, ModelDescriptor model)
    {
        ReportDiagnostics(context, model.Diagnostics);

        if (string.IsNullOrEmpty(model.FullModelTypeName))
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").AppendLine(model.Namespace);
            sb.AppendLine("{");
        }

        var indent = string.IsNullOrEmpty(model.Namespace) ? "" : "    ";
        var inner = indent + "    ";

        sb.Append(indent).Append("/// <summary>Generated reflection-free validator for <see cref=\"").Append(model.ModelName).AppendLine("\"/>.</summary>");
        sb.Append(indent).AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"eQuantic.Validation.Generator\", \"2.0.0\")]");
        sb.Append(indent).Append("public sealed class ").Append(model.GeneratedValidatorName)
            .Append(" : global::eQuantic.Validation.IValidator<").Append(model.FullModelTypeName)
            .AppendLine(">, global::eQuantic.Validation.IDescribableValidator");
        sb.Append(indent).AppendLine("{");

        EmitRegexFields(sb, inner, model);

        sb.Append(inner).AppendLine("/// <inheritdoc />");
        sb.Append(inner).Append("public global::System.Type ValidatedType => typeof(").Append(model.FullModelTypeName).AppendLine(");");
        sb.AppendLine();

        EmitValidateMethod(sb, inner, model, isAsync: false);
        sb.AppendLine();
        EmitValidateMethod(sb, inner, model, isAsync: true);
        sb.AppendLine();

        sb.Append(inner).AppendLine("global::eQuantic.Validation.ValidationResult global::eQuantic.Validation.IValidator.Validate(object instance, global::eQuantic.Validation.ValidationContext? context) =>");
        sb.Append(inner).Append("    instance is ").Append(model.FullModelTypeName).Append(" typed ? Validate(typed, context) : throw new global::System.ArgumentException($\"Expected an instance of '{typeof(").Append(model.FullModelTypeName).AppendLine(").FullName}'.\", nameof(instance));");
        sb.AppendLine();

        sb.Append(inner).AppendLine("global::System.Threading.Tasks.Task<global::eQuantic.Validation.ValidationResult> global::eQuantic.Validation.IValidator.ValidateAsync(object instance, global::eQuantic.Validation.ValidationContext? context, global::System.Threading.CancellationToken cancellationToken) =>");
        sb.Append(inner).Append("    instance is ").Append(model.FullModelTypeName).Append(" typed ? ValidateAsync(typed, context, cancellationToken) : throw new global::System.ArgumentException($\"Expected an instance of '{typeof(").Append(model.FullModelTypeName).AppendLine(").FullName}'.\", nameof(instance));");
        sb.AppendLine();

        EmitDescribe(sb, inner, model);
        sb.AppendLine();

        sb.Append(inner).AppendLine("private static global::eQuantic.Validation.ValidationFailure CreateFailure(global::eQuantic.Validation.ValidationContext context, string path, string displayName, string code, string template, global::eQuantic.Validation.ValidationSeverity severity, global::System.Collections.Generic.IReadOnlyDictionary<string, object?>? arguments)");
        sb.Append(inner).AppendLine("{");
        sb.Append(inner).AppendLine("    var message = global::eQuantic.Validation.ValidationMessages.Format(context, path, displayName, code, template, arguments);");
        sb.Append(inner).AppendLine("    return new global::eQuantic.Validation.ValidationFailure(path, code, message, severity, arguments);");
        sb.Append(inner).AppendLine("}");

        if (NeedsSequenceHelper(model))
        {
            sb.AppendLine();
            sb.Append(inner).AppendLine("private static bool IsEmptySequence(global::System.Collections.IEnumerable sequence)");
            sb.Append(inner).AppendLine("{");
            sb.Append(inner).AppendLine("    var enumerator = sequence.GetEnumerator();");
            sb.Append(inner).AppendLine("    try");
            sb.Append(inner).AppendLine("    {");
            sb.Append(inner).AppendLine("        return !enumerator.MoveNext();");
            sb.Append(inner).AppendLine("    }");
            sb.Append(inner).AppendLine("    finally");
            sb.Append(inner).AppendLine("    {");
            sb.Append(inner).AppendLine("        (enumerator as global::System.IDisposable)?.Dispose();");
            sb.Append(inner).AppendLine("    }");
            sb.Append(inner).AppendLine("}");
        }

        sb.Append(indent).AppendLine("}");

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine("}");
        }

        context.AddSource(model.HintName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitDescribe(StringBuilder sb, string indent, ModelDescriptor model)
    {
        sb.Append(indent).AppendLine("private static readonly global::eQuantic.Validation.ValidationRuleDescriptor[] RuleManifest =");
        sb.Append(indent).AppendLine("{");

        foreach (var property in model.Properties)
        {
            foreach (var rule in property.Rules)
            {
                sb.Append(indent).Append("    ").Append(BuildRuleDescriptorLiteral(property, rule)).AppendLine(",");
            }
        }

        sb.Append(indent).AppendLine("};");
        sb.AppendLine();
        sb.Append(indent).AppendLine("/// <summary>Returns the compile-time rule manifest of this validator.</summary>");
        sb.Append(indent).Append("public global::eQuantic.Validation.ValidatorDescription Describe() => new(typeof(")
            .Append(model.FullModelTypeName).AppendLine("), RuleManifest);");
    }

    private static string BuildRuleDescriptorLiteral(PropertyDescriptor property, RuleDescriptor rule)
    {
        var path = rule.Kind == RuleKind.ValidateEach
            ? property.PropertyName + "[]"
            : property.PropertyName;

        var kind = rule.Kind switch
        {
            RuleKind.Required => "required",
            RuleKind.NotEmpty => "not_empty",
            RuleKind.NotWhiteSpace => "not_whitespace",
            RuleKind.Email => "email",
            RuleKind.MinLength => "minimum_length",
            RuleKind.MaxLength => "maximum_length",
            RuleKind.Length => "length",
            RuleKind.Range => "inclusive_between",
            RuleKind.Pattern => "pattern",
            RuleKind.GreaterThan => "greater_than",
            RuleKind.LessThan => "less_than",
            RuleKind.ValidateNested => "nested",
            RuleKind.ValidateEach => "collection",
            _ => "predicate",
        };

        var severity = rule.Severity switch
        {
            1 => "global::eQuantic.Validation.ValidationSeverity.Warning",
            2 => "global::eQuantic.Validation.ValidationSeverity.Information",
            _ => "global::eQuantic.Validation.ValidationSeverity.Error",
        };

        var sb = new StringBuilder();
        sb.Append("new global::eQuantic.Validation.ValidationRuleDescriptor(\"")
            .Append(EscapeString(path)).Append("\", \"")
            .Append(kind).Append("\", \"")
            .Append(EscapeString(rule.Code)).Append("\", \"")
            .Append(EscapeString(rule.MessageTemplate)).Append("\", ")
            .Append(severity).Append(", ");

        if (rule.Arguments.Count == 0 && rule.Pattern is null)
        {
            sb.Append("null, ");
        }
        else
        {
            sb.Append("new global::System.Collections.Generic.Dictionary<string, object?> { ");
            var first = true;
            foreach (var argument in rule.Arguments)
            {
                if (!first)
                {
                    sb.Append(", ");
                }

                sb.Append("[\"").Append(EscapeString(argument.Name)).Append("\"] = ").Append(argument.CSharpLiteral);
                first = false;
            }

            if (rule.Pattern is not null)
            {
                if (!first)
                {
                    sb.Append(", ");
                }

                sb.Append("[\"Pattern\"] = @\"").Append(rule.Pattern.Replace("\"", "\"\"")).Append('"');
            }

            sb.Append(" }, ");
        }

        if (rule.Scenarios.Count == 0)
        {
            sb.Append("null, ");
        }
        else
        {
            sb.Append("new[] { ");
            for (var index = 0; index < rule.Scenarios.Count; index++)
            {
                if (index > 0)
                {
                    sb.Append(", ");
                }

                sb.Append('"').Append(EscapeString(rule.Scenarios[index])).Append('"');
            }

            sb.Append(" }, ");
        }

        sb.Append("false, false, valueType: typeof(").Append(property.BareTypeName).Append("))");
        return sb.ToString();
    }

    private static void ReportDiagnostics(SourceProductionContext context, EquatableArray<DiagnosticInfo> diagnostics)
    {
        foreach (var diagnostic in diagnostics)
        {
            var descriptor = diagnostic.Id switch
            {
                CustomRuleMethodMissingId => CustomRuleMethodMissing,
                ElementTypeUnresolvedId => ElementTypeUnresolved,
                _ => UnsupportedTarget,
            };

            context.ReportDiagnostic(Diagnostic.Create(descriptor, diagnostic.ToLocation(), diagnostic.Message));
        }
    }

    public static void EmitAccessorRegistrations(
        SourceProductionContext context,
        ImmutableArray<AccessorRegistrationDescriptor> descriptors,
        RegistrationCapabilities capabilities)
    {
        if (descriptors.IsEmpty || !capabilities.HasAccessorRegistry || !capabilities.HasModuleInitializer)
        {
            return;
        }

        var seen = new HashSet<string>(StringComparer.Ordinal);
        var registrations = new List<string>();
        foreach (var descriptor in descriptors)
        {
            foreach (var entry in descriptor.Entries)
            {
                if (!seen.Add(descriptor.ModelTypeName + "|" + entry.Path + "|" + entry.ValueTypeName))
                {
                    continue;
                }

                registrations.Add(
                    "        global::eQuantic.Validation.ValidatorAccessors.Register<" +
                    descriptor.ModelTypeName + ", " + entry.ValueTypeName + ">(\"" +
                    EscapeString(entry.Path) + "\", " + entry.AccessorBody + ");");
            }
        }

        if (registrations.Count == 0)
        {
            return;
        }

        registrations.Sort(StringComparer.Ordinal);

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace eQuantic.Validation.Generated;");
        source.AppendLine();
        source.AppendLine("/// <summary>Pre-compiled property accessors for this assembly's fluent validators.");
        source.AppendLine("/// Registered at module load so RuleFor never pays Expression.Compile at runtime.</summary>");
        source.AppendLine("internal static class ValidatorAccessorRegistrations");
        source.AppendLine("{");
        source.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        source.AppendLine("    internal static void Register()");
        source.AppendLine("    {");

        foreach (var registration in registrations)
        {
            source.AppendLine(registration);
        }

        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource("Validation.AccessorRegistrations.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static bool NeedsSequenceHelper(ModelDescriptor model)
    {
        foreach (var property in model.Properties)
        {
            foreach (var rule in property.Rules)
            {
                if (rule.Kind == RuleKind.NotEmpty && !property.IsString && property.IsNullableOrReference)
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static void EmitRegexFields(StringBuilder sb, string indent, ModelDescriptor model)
    {
        var emittedEmail = false;
        for (var propertyIndex = 0; propertyIndex < model.Properties.Count; propertyIndex++)
        {
            var property = model.Properties[propertyIndex];
            for (var ruleIndex = 0; ruleIndex < property.Rules.Count; ruleIndex++)
            {
                var rule = property.Rules[ruleIndex];
                if (rule.Kind == RuleKind.Email && !emittedEmail)
                {
                    sb.Append(indent).AppendLine("private static readonly global::System.Text.RegularExpressions.Regex EmailRegex = new(@\"^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$\", global::System.Text.RegularExpressions.RegexOptions.CultureInvariant);");
                    emittedEmail = true;
                }
                else if (rule.Kind == RuleKind.Pattern)
                {
                    sb.Append(indent)
                        .Append("private static readonly global::System.Text.RegularExpressions.Regex ")
                        .Append(PatternFieldName(property.PropertyName, ruleIndex))
                        .Append(" = new(@\"")
                        .Append((rule.Pattern ?? string.Empty).Replace("\"", "\"\""))
                        .AppendLine("\", global::System.Text.RegularExpressions.RegexOptions.CultureInvariant);");
                }
            }
        }

        if (emittedEmail || model.Properties.Any(static property => property.Rules.Any(static rule => rule.Kind == RuleKind.Pattern)))
        {
            sb.AppendLine();
        }
    }

    private static string PatternFieldName(string propertyName, int ruleIndex) =>
        "PatternRegex_" + propertyName + "_" + ruleIndex.ToString(System.Globalization.CultureInfo.InvariantCulture);

    private static void EmitValidateMethod(StringBuilder sb, string indent, ModelDescriptor model, bool isAsync)
    {
        sb.Append(indent).AppendLine("/// <inheritdoc />");
        if (isAsync)
        {
            sb.Append(indent).Append("public async global::System.Threading.Tasks.Task<global::eQuantic.Validation.ValidationResult> ValidateAsync(")
                .Append(model.FullModelTypeName).AppendLine(" instance, global::eQuantic.Validation.ValidationContext? context = null, global::System.Threading.CancellationToken cancellationToken = default)");
        }
        else
        {
            sb.Append(indent).Append("public global::eQuantic.Validation.ValidationResult Validate(")
                .Append(model.FullModelTypeName).AppendLine(" instance, global::eQuantic.Validation.ValidationContext? context = null)");
        }

        sb.Append(indent).AppendLine("{");
        var body = indent + "    ";

        if (model.IsReferenceType)
        {
            sb.Append(body).AppendLine("if (instance is null)");
            sb.Append(body).AppendLine("{");
            sb.Append(body).AppendLine("    return global::eQuantic.Validation.ValidationResult.Failure(");
            sb.Append(body).AppendLine("        new global::eQuantic.Validation.ValidationFailure(string.Empty, global::eQuantic.Validation.ValidationCodes.Required, \"The instance is required.\"));");
            sb.Append(body).AppendLine("}");
            sb.AppendLine();
        }

        if (isAsync)
        {
            sb.Append(body).AppendLine("cancellationToken.ThrowIfCancellationRequested();");
        }

        sb.Append(body).AppendLine("var effectiveContext = context ?? global::eQuantic.Validation.ValidationContext.Default;");
        sb.Append(body).AppendLine("var failures = new global::System.Collections.Generic.List<global::eQuantic.Validation.ValidationFailure>();");
        sb.AppendLine();

        foreach (var property in model.Properties)
        {
            EmitPropertyBlock(sb, body, property, isAsync);
        }

        sb.Append(body).AppendLine("return failures.Count == 0 ? global::eQuantic.Validation.ValidationResult.Success : new global::eQuantic.Validation.ValidationResult(failures);");
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitPropertyBlock(StringBuilder sb, string indent, PropertyDescriptor property, bool isAsync)
    {
        sb.Append(indent).Append("// ---- Property: ").Append(property.PropertyName).AppendLine(" ----");
        sb.Append(indent).Append("if (effectiveContext.IncludesPath(\"").Append(property.PropertyName).AppendLine("\"))");
        sb.Append(indent).AppendLine("{");

        var body = indent + "    ";
        sb.Append(body).Append("var val = instance.").Append(property.PropertyName).AppendLine(";");

        for (var ruleIndex = 0; ruleIndex < property.Rules.Count; ruleIndex++)
        {
            EmitRule(sb, body, property, property.Rules[ruleIndex], ruleIndex, isAsync);
        }

        sb.Append(indent).AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitRule(
        StringBuilder sb,
        string indent,
        PropertyDescriptor property,
        RuleDescriptor rule,
        int ruleIndex,
        bool isAsync)
    {
        var scenarioCondition = BuildScenarioCondition(rule.Scenarios);
        if (scenarioCondition.Length > 0)
        {
            sb.Append(indent).Append("if (").Append(scenarioCondition).AppendLine(")");
            sb.Append(indent).AppendLine("{");
            indent += "    ";
        }

        switch (rule.Kind)
        {
            case RuleKind.ValidateNested:
                EmitValidateNested(sb, indent, property, isAsync);
                break;
            case RuleKind.ValidateEach:
                EmitValidateEach(sb, indent, property, rule, isAsync);
                break;
            default:
                EmitCheckRule(sb, indent, property, rule, ruleIndex);
                break;
        }

        if (scenarioCondition.Length > 0)
        {
            sb.Append(indent.Substring(4)).AppendLine("}");
        }
    }

    private static void EmitCheckRule(
        StringBuilder sb,
        string indent,
        PropertyDescriptor property,
        RuleDescriptor rule,
        int ruleIndex)
    {
        var condition = BuildFailureCondition(property, rule, ruleIndex);
        if (condition is null)
        {
            return;
        }

        sb.Append(indent).Append("if (").Append(condition).AppendLine(")");
        sb.Append(indent).Append("    failures.Add(").Append(BuildCreateFailureCall(property, rule)).AppendLine(");");
    }

    private static string? BuildFailureCondition(PropertyDescriptor property, RuleDescriptor rule, int ruleIndex)
    {
        var variableSuffix = "_r" + ruleIndex.ToString(System.Globalization.CultureInfo.InvariantCulture);
        switch (rule.Kind)
        {
            case RuleKind.Required:
                if (property.IsString)
                {
                    return "string.IsNullOrWhiteSpace(val)";
                }

                if (property.IsNullableOrReference)
                {
                    return "val is null";
                }

                return "global::System.Collections.Generic.EqualityComparer<" + property.TypeName + ">.Default.Equals(val, default(" + property.TypeName + "))";

            case RuleKind.NotEmpty:
                if (property.IsString)
                {
                    return "string.IsNullOrEmpty(val)";
                }

                if (property.IsNullableOrReference)
                {
                    return "val is null || (val is global::System.Collections.IEnumerable sequence" + variableSuffix + " && IsEmptySequence(sequence" + variableSuffix + "))";
                }

                return "global::System.Collections.Generic.EqualityComparer<" + property.TypeName + ">.Default.Equals(val, default(" + property.TypeName + "))";

            case RuleKind.NotWhiteSpace:
                return "string.IsNullOrWhiteSpace(val)";

            case RuleKind.Email:
                return "val is not null && !EmailRegex.IsMatch(val)";

            case RuleKind.MinLength:
            {
                var minimum = GetArgument(rule, "MinimumLength");
                return property.IsString
                    ? "val is not null && val.Length < " + minimum
                    : "val is global::System.Collections.ICollection collection" + variableSuffix + " && collection" + variableSuffix + ".Count < " + minimum;
            }

            case RuleKind.MaxLength:
            {
                var maximum = GetArgument(rule, "MaximumLength");
                return property.IsString
                    ? "val is not null && val.Length > " + maximum
                    : "val is global::System.Collections.ICollection collection" + variableSuffix + " && collection" + variableSuffix + ".Count > " + maximum;
            }

            case RuleKind.Length:
            {
                var minimum = GetArgument(rule, "MinimumLength");
                var maximum = GetArgument(rule, "MaximumLength");
                return property.IsString
                    ? "val is not null && (val.Length < " + minimum + " || val.Length > " + maximum + ")"
                    : "val is global::System.Collections.ICollection collection" + variableSuffix + " && (collection" + variableSuffix + ".Count < " + minimum + " || collection" + variableSuffix + ".Count > " + maximum + ")";
            }

            case RuleKind.Range:
                return "val < " + GetArgument(rule, "Minimum") + " || val > " + GetArgument(rule, "Maximum");

            case RuleKind.GreaterThan:
                return "val <= " + GetArgument(rule, "Minimum");

            case RuleKind.LessThan:
                return "val >= " + GetArgument(rule, "Maximum");

            case RuleKind.Pattern:
                return "val is not null && !" + PatternFieldName(property.PropertyName, ruleIndex) + ".IsMatch(val)";

            case RuleKind.CustomRule:
                if (string.IsNullOrEmpty(rule.CustomMethodName))
                {
                    return null;
                }

                return string.IsNullOrEmpty(rule.CustomDeclaringType)
                    ? "!instance." + rule.CustomMethodName + "(val)"
                    : "!" + rule.CustomDeclaringType + "." + rule.CustomMethodName + "(instance, val)";

            default:
                return null;
        }
    }

    private static string BuildCreateFailureCall(PropertyDescriptor property, RuleDescriptor rule)
    {
        var severity = rule.Severity switch
        {
            1 => "global::eQuantic.Validation.ValidationSeverity.Warning",
            2 => "global::eQuantic.Validation.ValidationSeverity.Information",
            _ => "global::eQuantic.Validation.ValidationSeverity.Error",
        };

        var sb = new StringBuilder();
        sb.Append("CreateFailure(effectiveContext, \"")
            .Append(property.PropertyName)
            .Append("\", \"")
            .Append(property.PropertyName)
            .Append("\", \"")
            .Append(EscapeString(rule.Code))
            .Append("\", \"")
            .Append(EscapeString(rule.MessageTemplate))
            .Append("\", ")
            .Append(severity)
            .Append(", ");

        if (rule.Arguments.Count == 0)
        {
            sb.Append("null");
        }
        else
        {
            sb.Append("new global::System.Collections.Generic.Dictionary<string, object?> { ");
            for (var index = 0; index < rule.Arguments.Count; index++)
            {
                var argument = rule.Arguments[index];
                if (index > 0)
                {
                    sb.Append(", ");
                }

                sb.Append("[\"").Append(EscapeString(argument.Name)).Append("\"] = ").Append(argument.CSharpLiteral);
            }

            sb.Append(" }");
        }

        sb.Append(')');
        return sb.ToString();
    }

    private static void EmitValidateNested(StringBuilder sb, string indent, PropertyDescriptor property, bool isAsync)
    {
        var validatorType = "global::eQuantic.Validation.IValidator<" + property.BareTypeName + ">";
        sb.Append(indent).AppendLine("if (val is not null)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    var childValidator = effectiveContext.GetService<").Append(validatorType).AppendLine(">();");
        sb.Append(indent).AppendLine("    if (childValidator is not null)");
        sb.Append(indent).AppendLine("    {");
        if (isAsync)
        {
            sb.Append(indent).Append("        var childResult = await childValidator.ValidateAsync(val, effectiveContext.CreateChildScope(\"").Append(property.PropertyName).AppendLine("\"), cancellationToken).ConfigureAwait(false);");
        }
        else
        {
            sb.Append(indent).Append("        var childResult = childValidator.Validate(val, effectiveContext.CreateChildScope(\"").Append(property.PropertyName).AppendLine("\"));");
        }

        sb.Append(indent).AppendLine("        foreach (var failure in childResult.Failures)");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).Append("            failures.Add(failure.WithPathPrefix(\"").Append(property.PropertyName).AppendLine("\"));");
        sb.Append(indent).AppendLine("        }");
        sb.Append(indent).AppendLine("    }");
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitValidateEach(StringBuilder sb, string indent, PropertyDescriptor property, RuleDescriptor rule, bool isAsync)
    {
        // The element type is known at compile time, so the child validator resolves through the
        // typed IValidator<TElement> service: no MakeGenericType, trimming- and AOT-safe.
        var validatorType = "global::eQuantic.Validation.IValidator<" + rule.ElementTypeName + ">";
        sb.Append(indent).AppendLine("if (val is not null)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    var itemValidator = effectiveContext.GetService<").Append(validatorType).AppendLine(">();");
        sb.Append(indent).AppendLine("    if (itemValidator is not null)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        var index = 0;");
        sb.Append(indent).AppendLine("        foreach (var element in val)");
        sb.Append(indent).AppendLine("        {");
        if (isAsync)
        {
            sb.Append(indent).AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
        }

        sb.Append(indent).Append("            var itemPath = \"").Append(property.PropertyName).AppendLine("[\" + index.ToString(global::System.Globalization.CultureInfo.InvariantCulture) + \"]\";");
        sb.Append(indent).AppendLine("            if (element is not null && effectiveContext.IncludesPath(itemPath))");
        sb.Append(indent).AppendLine("            {");
        if (isAsync)
        {
            sb.Append(indent).AppendLine("                var itemResult = await itemValidator.ValidateAsync(element, effectiveContext.CreateChildScope(itemPath), cancellationToken).ConfigureAwait(false);");
        }
        else
        {
            sb.Append(indent).AppendLine("                var itemResult = itemValidator.Validate(element, effectiveContext.CreateChildScope(itemPath));");
        }

        sb.Append(indent).AppendLine("                foreach (var failure in itemResult.Failures)");
        sb.Append(indent).AppendLine("                {");
        sb.Append(indent).AppendLine("                    failures.Add(failure.WithPathPrefix(itemPath));");
        sb.Append(indent).AppendLine("                }");
        sb.Append(indent).AppendLine("            }");
        sb.Append(indent).AppendLine("            index++;");
        sb.Append(indent).AppendLine("        }");
        sb.Append(indent).AppendLine("    }");
        sb.Append(indent).AppendLine("}");
    }

    private static string BuildScenarioCondition(EquatableArray<string> scenarios)
    {
        if (scenarios.Count == 0)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        for (var index = 0; index < scenarios.Count; index++)
        {
            if (index > 0)
            {
                sb.Append(" || ");
            }

            // Case-insensitive to match ValidationContext scenario semantics.
            sb.Append("global::System.Linq.Enumerable.Contains(effectiveContext.Scenarios, \"")
                .Append(EscapeString(scenarios[index]))
                .Append("\", global::System.StringComparer.OrdinalIgnoreCase)");
        }

        return sb.ToString();
    }

    private static string GetArgument(RuleDescriptor rule, string name)
    {
        foreach (var argument in rule.Arguments)
        {
            if (argument.Name == name)
            {
                return argument.CSharpLiteral;
            }
        }

        return "0";
    }

    private static string EscapeString(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", string.Empty).Replace("\n", string.Empty);

    public static void EmitRegistrations(
        SourceProductionContext context,
        ImmutableArray<ValidatorDescriptor> manualValidators,
        ImmutableArray<ModelDescriptor> generatedModels,
        RegistrationCapabilities capabilities)
    {
        var all = new List<ValidatorDescriptor>(manualValidators);
        foreach (var model in generatedModels)
        {
            if (!string.IsNullOrEmpty(model.FullGeneratedValidatorTypeName))
            {
                all.Add(new ValidatorDescriptor(model.FullGeneratedValidatorTypeName, model.FullModelTypeName));
            }
        }

        var distinctValidators = all
            .Distinct()
            .OrderBy(static descriptor => descriptor.ValidatorType, StringComparer.Ordinal)
            .ToArray();

        if (distinctValidators.Length == 0)
        {
            return;
        }

        if (!capabilities.HasCorePackage || !capabilities.HasServiceCollection)
        {
            context.ReportDiagnostic(Diagnostic.Create(MissingRegistrationDependencies, Location.None));
            return;
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace eQuantic.Validation.Generated;");
        source.AppendLine();
        source.AppendLine("/// <summary>Registers validators declared or generated in this assembly. Internal by design:");
        source.AppendLine("/// each assembly opts in by calling its own AddGeneratedValidation, so referencing a library");
        source.AppendLine("/// never registers validators behind the caller's back.</summary>");
        source.AppendLine("internal static class ValidationGeneratedExtensions");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>Registers this assembly's validators as scoped services.</summary>");
        source.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedValidation(");
        source.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        source.AppendLine("    {");
        source.AppendLine("        if (services is null) throw new global::System.ArgumentNullException(nameof(services));");
        source.AppendLine("        global::eQuantic.Validation.ServiceCollectionExtensions.AddValidationDispatcher(services);");

        foreach (var validator in distinctValidators)
        {
            source.Append("        global::eQuantic.Validation.ServiceCollectionExtensions.AddValidator<")
                .Append(validator.ModelType)
                .Append(", ")
                .Append(validator.ValidatorType)
                .AppendLine(">(services);");
        }

        source.AppendLine("        return services;");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource("Validation.GeneratedRegistrations.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }
}
